server:
  port: 8080
security:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://localhost/login/oauth/access_token
      userAuthorizationUri: https://localhost/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://localhost/user
      preferTokenInfo: false
