auth-server: http://localhost:8080
server:
  port: 8082
security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      use-current-uri: false
    resource:
      user-info-uri: ${auth-server}/user
      token-info-uri: ${auth-server}/oauth/check_token
logging:
  level:
    org.springframework: debug