server:
  port: 8081
security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      use-current-uri: false
    resource:
      user-info-uri: http://localhost:8080/user # 从授权服务器获取当前登录用户信息的地址
logging:
  level:
    org.springframework: debug