auth-server: http://localhost:8080
server:
  port: 8081
security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      use-current-uri: false
    resource:
      user-info-uri: ${auth-server}/user # 从授权服务器获取当前登录用户信息的地址
      token-info-uri: ${auth-server}/oauth/check_token
      jwt:
        key-uri: ${auth-server}/oauth/token_key
logging:
  level:
    org.springframework: debug